version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      container_name: next.js
    volumes: 
    - next_build:/frontend/.next
  backend:
    build: 
      context: ./backend
      container_name: django
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - pgdb
  pgdb:
      image: postgres
      container_name: pgdb
      environment:
        POSTGRES_DB: "${DATABASE_NAME}"
        POSTGRES_USER: "${DATABASE_USER}"
        POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      volumes:
        - pgdata:/var/lib/postgressql/data/
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - next_build::/var/www/nextjs
    depends_on:
      - backend
      - frontend
volumes:
    next_build:
    pgdata:
