# Generated by Django 4.1.1 on 2022-10-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_technology_project_technologies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
    ]
