# Generated by Django 4.1.1 on 2022-10-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='image')),
                ('alt', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet', models.CharField(max_length=250)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience.experience')),
            ],
            options={
                'verbose_name_plural': 'Bullets',
            },
        ),
    ]
