# Generated by Django 4.1.1 on 2022-10-04 01:35

from django.db import migrations, models
import experience.validators


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='logo',
            field=models.ImageField(upload_to='image', validators=[experience.validators.validate_file_extension]),
        ),
    ]
